baseURL: "http://edmattwhite.github.io/"
languageCode: "en-gb"
title: "Ed's Blog"
theme: "ween"
defaultMarkdownHandler: pandoc

params:
  author: "Edward White"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3

security:
  enableInlineShortcodes: true
  exec:
    allow:
    - ^asciidoctor
    - ^pandoc
    osEnv:
    - .*
  funcs:
    getenv:
    - ^INFINITEINKROOT$
